-- Phase 1 Deliverable: Finalized PostgreSQL Schema with Template for Multi-Tenancy
-- This file is now intended for data seeding or non-DDL operations, as schema creation
-- is handled by TypeORM migrations.
