// ─── Reference guides (docs) — sourced from repo-root /docs markdown ─────────
// These mirror the user-guide files that power the /docs renderer. pageKey is
// the real app route each guide documents; roles scope it to persona paths.

import type { CurriculumGuide } from './types';

export const GUIDE_CATEGORIES = [
  'Product',
  'Getting Started',
  'Dashboards',
  'Financial Control',
  'Projects',
  'Operations',
  'Reporting',
  'Administration',
] as const;

export const CURRICULUM_GUIDES: CurriculumGuide[] = [
  {
    slug: 'product-manual',
    title: 'Product Manual',
    category: 'Product',
    description:
      'Self-contained guide to every SentinelFi capability, workflow, and role, from onboarding to enterprise deployment.',
    filePath: 'product/PRODUCT_DOCUMENTATION.md',
    pageKey: '/training',
    roles: ['tenant-admin', 'executive', 'finance-ops', 'project-manager', 'auditor'],
    order: 0,
  },
  {
    slug: '00-quick-start',
    title: 'Quick Start: Your First 5 Steps',
    category: 'Getting Started',
    description: 'Sign up, first login, and your first project.',
    filePath: 'product/user-guides/00-QUICK-START.md',
    pageKey: '/dashboard/home',
    roles: ['tenant-admin'],
    order: 1,
  },
  {
    slug: '01-dashboard-home',
    title: 'The Home Dashboard',
    category: 'Dashboards',
    description: 'Your daily command centre and headline metrics.',
    filePath: 'product/user-guides/01-DASHBOARD-HOME.md',
    pageKey: '/dashboard/home',
    roles: ['executive', 'finance-ops', 'tenant-admin'],
    order: 2,
  },
  {
    slug: '02-ceo-dashboard',
    title: 'CEO High-Fidelity Dashboard',
    category: 'Dashboards',
    description: 'Executive-level portfolio and financial overview.',
    filePath: 'product/user-guides/02-CEO-DASHBOARD.md',
    pageKey: '/dashboard/ceo',
    roles: ['executive'],
    order: 3,
  },
  {
    slug: '03-financial-intelligence',
    title: 'Financial Intelligence Hub',
    category: 'Financial Control',
    description: 'CAPEX/OPEX intelligence, variance, and analysis.',
    filePath: 'product/user-guides/03-FINANCIAL-INTELLIGENCE.md',
    pageKey: '/financials/intelligence',
    roles: ['executive', 'finance-ops', 'auditor'],
    order: 4,
  },
  {
    slug: '04-governance-hub',
    title: 'Governance Hub and Approvals',
    category: 'Financial Control',
    description: 'Multi-level approval workflows and delegation of authority.',
    filePath: 'product/user-guides/04-GOVERNANCE-HUB.md',
    pageKey: '/financials/approvals',
    roles: ['finance-ops', 'tenant-admin', 'auditor'],
    order: 5,
  },
  {
    slug: '05-audit-trail',
    title: 'The Audit Trail',
    category: 'Financial Control',
    description: 'Reviewing every recorded action and change.',
    filePath: 'product/user-guides/05-AUDIT-TRAIL.md',
    pageKey: '/admin/audit-log',
    roles: ['auditor', 'tenant-admin'],
    order: 6,
  },
  {
    slug: '06-project-portfolio',
    title: 'Project Portfolio Management',
    category: 'Projects',
    description: 'Creating, browsing, and tracking projects.',
    filePath: 'product/user-guides/06-PROJECT-PORTFOLIO.md',
    pageKey: '/financials/projects',
    roles: ['project-manager', 'finance-ops', 'executive'],
    order: 7,
  },
  {
    slug: '07-wbs-designer',
    title: 'The WBS Designer',
    category: 'Projects',
    description: 'Building work breakdown structures and budget lines.',
    filePath: 'product/user-guides/07-WBS-DESIGNER.md',
    pageKey: '/financials/projects/wbs',
    roles: ['project-manager', 'finance-ops'],
    order: 8,
  },
  {
    slug: '08-project-budgeting',
    title: 'Project Budgeting',
    category: 'Projects',
    description: 'Allocating and approving project budgets.',
    filePath: 'product/user-guides/08-PROJECT-BUDGETING.md',
    pageKey: '/financials/projects/budgets',
    roles: ['project-manager', 'finance-ops'],
    order: 9,
  },
  {
    slug: '09-logging-expenses',
    title: 'Logging Expenses',
    category: 'Projects',
    description: 'Recording, categorising, and submitting expenses.',
    filePath: 'product/user-guides/09-LOGGING-EXPENSES.md',
    pageKey: '/financials/expenses/new',
    roles: ['project-manager', 'finance-ops'],
    order: 10,
  },
  {
    slug: '10-p2p-procurement',
    title: 'P2P Procurement Lifecycle',
    category: 'Operations',
    description: 'Requisitions, purchase orders, and invoices.',
    filePath: 'product/user-guides/10-P2P-PROCUREMENT.md',
    pageKey: '/financials/operations/procurement',
    roles: ['project-manager', 'finance-ops'],
    order: 11,
  },
  {
    slug: '11-opex-planning',
    title: 'OPEX Planning and Departmental Budgets',
    category: 'Operations',
    description: 'Departmental operating expense planning.',
    filePath: 'product/user-guides/11-OPEX-PLANNING.md',
    pageKey: '/financials/operations/planning',
    roles: ['finance-ops', 'tenant-admin'],
    order: 12,
  },
  {
    slug: '12-payroll-desk',
    title: 'The Payroll Desk',
    category: 'Operations',
    description: 'Running payroll cycles and managing staff payments.',
    filePath: 'product/user-guides/12-PAYROLL-DESK.md',
    pageKey: '/financials/operations/payroll',
    roles: ['finance-ops'],
    order: 13,
  },
  {
    slug: '13-fiscal-setup',
    title: 'Fiscal Setup and Categories',
    category: 'Operations',
    description: 'Fiscal years, periods, and expense categories.',
    filePath: 'product/user-guides/13-FISCAL-SETUP.md',
    pageKey: '/financials/operations/setup',
    roles: ['tenant-admin', 'finance-ops'],
    order: 14,
  },
  {
    slug: '14-reporting-hub',
    title: 'Reporting and AI Hub',
    category: 'Reporting',
    description: 'Generating reports and AI-assisted narratives.',
    filePath: 'product/user-guides/14-REPORTING-HUB.md',
    pageKey: '/reporting',
    roles: ['executive', 'finance-ops', 'auditor'],
    order: 15,
  },
  {
    slug: '15-document-archive',
    title: 'Document Archive and Retrieval',
    category: 'Reporting',
    description: 'Uploading, storing, and retrieving documents.',
    filePath: 'product/user-guides/15-DOCUMENT-ARCHIVE.md',
    pageKey: '/reporting/archive',
    roles: ['finance-ops', 'auditor'],
    order: 16,
  },
  {
    slug: '16-superadmin-controls',
    title: 'SuperAdmin Controls',
    category: 'Administration',
    description: 'Platform-level tenant and system management.',
    filePath: 'product/user-guides/16-SUPERADMIN-CONTROLS.md',
    pageKey: '/super',
    roles: ['tenant-admin'],
    order: 17,
  },
  {
    slug: '17-ai-communication',
    title: 'AI Communication and Messaging',
    category: 'Administration',
    description: 'The AI assistant, alerts, and team messaging.',
    filePath: 'product/user-guides/17-AI-COMMUNICATION.md',
    pageKey: '/financials/intelligence',
    roles: ['tenant-admin', 'finance-ops'],
    order: 18,
  },
];

export function getCurriculumGuide(slug: string): CurriculumGuide | undefined {
  return CURRICULUM_GUIDES.find((g) => g.slug === slug);
}

export function getGuideForPageKey(pageKey: string): CurriculumGuide | undefined {
  const key = pageKey.startsWith('/') ? pageKey : `/${pageKey}`;
  return CURRICULUM_GUIDES.find((g) => g.pageKey === key);
}