export enum IndustryType {
  IT = 'IT',
  CONSTRUCTION = 'CONSTRUCTION',
  OIL_GAS = 'OIL_GAS',
  REAL_ESTATE = 'REAL_ESTATE',
  MANUFACTURING = 'MANUFACTURING',
  TELECOM = 'TELECOM',
  RENEWABLES = 'RENEWABLES',
  HEALTHCARE = 'HEALTHCARE',
  MINING = 'MINING',
  GENERAL = 'GENERAL',
}
